### PR TITLE
fixes Autoblock copyright #54

### LINKED ISSUE #54: Autoblock copyright
~Each blog article has a copyright. This could be autoblocked. 

`© 2020 ServiceNow, Inc. All rights reserved. ServiceNow, the ServiceNow logo, Now, and other ServiceNow marks are trademarks and/or registered trademarks of ServiceNow, Inc. in the United States and/or other countries. Other company names, product names, and logos may be trademarks of the respective companies with which they are associated.`

### PR DESCRIPTION
**Pull request by benpeter**
Fix #54 

Test URLs:
- Before: https://main--servicenow--hlxsites.hlx.live/blogs/2023/demo/better-employee-onboarding-day-1
- After: https://54--servicenow--hlxsites.hlx.live/blogs/2023/demo/better-employee-onboarding-day-1

### CODE REVIEW

File: blocks/article-copyright/article-copyright.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+import { getMetadata } from '../../scripts/aem.js';
+import { getLocaleInfo } from '../../scripts/scripts.js';
+
+export default async function decorate(block) {
+  const copyrightPath = getMetadata('copyright-path');
```
Comment (andreituicu) [inline blocks/article-copyright/article-copyright.js:5]: to keep it simple and follow YAGNI, I would go with having this path hardcoded rather than reading metadata.
if the authors want to see how a new copyright message looks like, they will simply preview first the changes and see them in `.page`.
at least at the moment, I don't see when would we need to have it configurable per article.

File: blocks/article-copyright/article-copyright.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+    : 'article-copyright';
+
+  const copyrightPromise = fetch(`${localeInfo.urlPrefix}/blogs/fragments/${copyrightFragmentPath}.plain.html`);
+
+  const publicationDate = getMetadata('publication-date');
+  const d = new Date(publicationDate);
+  const year = d.toLocaleDateString('en', { year: 'numeric' });
+
+  const copyrightFragment = await copyrightPromise;
+  const copyrightText = (await copyrightFragment.text()).replace('#year#', year);
```
Comment (andreituicu) [inline blocks/article-copyright/article-copyright.js:19]: could we please also check if the response is ok before accessing the .`text()`?

**Review by andreituicu — APPROVED** [review]
LGTM
